kind: HTTPScaledObject
apiVersion: http.keda.sh/v1alpha1
metadata:
    name: http-scaling-hello-prod
spec:
    hosts: 
      - hello-prod.kcan.io
    targetPendingRequests: 2
    scaledownPeriod: 30
    scaleTargetRef:
        deployment: deployment-hello-prod
        service: service-hello-prod
        port: 8080
    replicas:
        min: 1
        max: 4
