apiVersion: v1
kind: Service
metadata:
  name: service-hello-prod
spec:
  type: NodePort
  selector:
    app: hello-prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31070
